import {$WebType, None} from '#wexen';
import {Brand, Model} from 'rtt';

export type HttpHeaders = Model &
  Brand<'Web.HttpHeaders'> & {
    items: HttpHeaderList & Record<string, string | string[] | undefined>;

    get(key: string): string | string[] | None;
    set(key: string, value: string | string[] | None): void;
  };

export const $HttpHeaders = () => $WebType<HttpHeaders>('HttpHeaders');

export type HttpHeaderList = {
  Accept?: string | string[] | undefined;
  'Accept-Charset'?: string | string[] | undefined;
  'Accept-Encoding'?: string | string[] | undefined;
  'Accept-Language'?: string | string[] | undefined;
  'Accept-Ranges'?: string | undefined;
  'Access-Control-Allow-Credentials'?: string | undefined;
  'Access-Control-Allow-Headers'?: string | undefined;
  'Access-Control-Allow-Methods'?: string | undefined;
  'Access-Control-Allow-Origin'?: string | undefined;
  'Access-Control-Expose-Headers'?: string | undefined;
  'Access-Control-Max-Age'?: string | undefined;
  'Access-Control-Request-Headers'?: string | undefined;
  'Access-Control-Request-Method'?: string | undefined;
  Age?: string | undefined;
  Allow?: string | undefined;
  Authorization?: string | undefined;
  'Cache-Control'?: string | undefined;
  'Cdn-Cache-Control'?: string | undefined;
  Connection?: string | string[] | undefined;
  'Content-Disposition'?: string | undefined;
  'Content-Encoding'?: string | undefined;
  'Content-Language'?: string | undefined;
  'Content-Length'?: string | number | undefined;
  'Content-Location'?: string | undefined;
  'Content-Range'?: string | undefined;
  'Content-Security-Policy'?: string | undefined;
  'Content-Security-Policy-Report-Only'?: string | undefined;
  'Content-Type'?: string | undefined;
  Cookie?: string | string[] | undefined;
  Date?: string | undefined;
  Dav?: string | string[] | undefined;
  Dnt?: string | undefined;
  Etag?: string | undefined;
  Expect?: string | undefined;
  Expires?: string | undefined;
  Forwarded?: string | undefined;
  From?: string | undefined;
  Host?: string | undefined;
  'If-Match'?: string | undefined;
  'If-Modified-Since'?: string | undefined;
  'If-None-Match'?: string | undefined;
  'If-Range'?: string | undefined;
  'If-Unmodified-Since'?: string | undefined;
  'Last-Modified'?: string | undefined;
  Link?: string | string[] | undefined;
  Location?: string | undefined;
  'Max-Forwards'?: string | undefined;
  Origin?: string | undefined;
  Pragma?: string | string[] | undefined;
  'Proxy-Authenticate'?: string | string[] | undefined;
  'Proxy-Authorization'?: string | undefined;
  'Public-Key-Pins'?: string | undefined;
  'Public-Key-Pins-Report-Only'?: string | undefined;
  Range?: string | undefined;
  Referer?: string | undefined;
  'Referrer-Policy'?: string | undefined;
  Refresh?: string | undefined;
  'Retry-After'?: string | undefined;
  'Sec-Websocket-Accept'?: string | undefined;
  'Sec-Websocket-Extensions'?: string | string[] | undefined;
  'Sec-Websocket-Key'?: string | undefined;
  'Sec-Websocket-Protocol'?: string | string[] | undefined;
  'Sec-Websocket-Version'?: string | undefined;
  Server?: string | undefined;
  'Set-Cookie'?: string | string[] | undefined;
  'Strict-Transport-Security'?: string | undefined;
  TE?: string | undefined;
  Trailer?: string | undefined;
  'Transfer-Encoding'?: string | undefined;
  Upgrade?: string | undefined;
  'Upgrade-Insecure-Requests'?: string | undefined;
  'User-Agent'?: string | undefined;
  Vary?: string | undefined;
  Via?: string | string[] | undefined;
  Warning?: string | undefined;
  'WWW-Authenticate'?: string | string[] | undefined;
  'X-Content-Type-Options'?: string | undefined;
  'X-DNS-Prefetch-Control'?: string | undefined;
  'X-Frame-Options'?: string | undefined;
  'X-XSS-Protection'?: string | undefined;
};
